### ISSUE TITLE
Change text to "Search Google for Image"

### ISSUE THREAD

**Issue by shiftsayan** [Sukigu/search-by-image-on-google#2]
This makes the extension consistent with what Chrome offers and (in my subjective opinion) sounds a little better.

**Comment by Sukigu** [comment]
Sorry for taking so long to reply, but thanks for your suggestion!

The context menu option text has been updated as of 08af388c9a1c3bf0da3346715b979b58fd1a4463 and it will appear in the next version of the extension.
