### ISSUE TITLE
Is explicitly specifying 'index' needed?

### ISSUE THREAD

**Issue by quasicomputational** [Sukigu/search-by-image-on-google#5]
At line 20 of background.js, the invocation of `browser.tabs.create` is explicitly given the `index` argument. This makes the image search tab open up adjacent to the tab it's invoked from.

However, I have the `browser.tabs.insertRelatedAfterCurrent` setting set to false, which means that I expect new tabs to be opened at the end; hence, this extension is not behaving in accordance with the rest of Firefox for me.

If this is working as intended, that's fine; I'll go put together the twelve LoC or so to get an extension that works like I'd like it to. However, I suspect that just not specifying `index` will make the extension do the right thing in all circumstances.

**Comment by Sukigu** [comment]
Hey there! `index` is not required, but not setting it creates the new tab at the end of the tab bar. This would create the opposite effect (users with `browser.tabs.insertRelatedAfterCurrent` set to `true`, the default, would experience a different behavior than they're used to). However, I noticed that I can instead set `openerTabId` to explicitly set the current tab as the new tab's opener, which will in turn make the browser comply with the preference!

This is already live as of v1.6. Thanks for your input!

**Comment by quasicomputational** [comment]
LGTM, thanks!
