### ISSUE TITLE
Image URL not escaped

### ISSUE THREAD

**Issue by quasicomputational** [Sukigu/search-by-image-on-google#6]
Consider an image with an url like `https://example.com/image.jpeg?height=800&width=600`. The image search URL requested is going to be `https://www.google.com/searchbyimage?image_url=https://example.com/image.jpeg?height=800&width=600` - note that the `?` and `&` are unescaped, so there's no (principled) way for Google to identify the original URL versus what's a genuine parameter being passed for its own receipt. The image URL ought to be explicitly query-encoded before the request URL is constructed.

**Comment by Sukigu** [comment]
This has been fixed with v1.6. Currently, I'm only escaping `?` and `&`, so I'm not URL encoding the whole address, but I hope that's enough. If not, I can reopen this. Thanks again!

**Comment by quasicomputational** [comment]
`#` will need to be escaped as well, I think. I generally reach for `encodeURIComponent` because someone more thorough than I have has already done the work of figuring out which characters are safe and which aren't.
